packages:
  - 'apps/*'
  - 'services/*'
  - 'packages/*'

overrides:
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5
  iconv-lite: ^0.6.3

onlyBuiltDependencies:
  - onnxruntime-node
  - protobufjs
  - sharp

patchedDependencies:
  expo-localization@15.0.3: patches/expo-localization@15.0.3.patch

allowBuilds:
  onnxruntime-node: true
  protobufjs: true
  sharp: true
