export const testUser = {
  id: 'user-e2e-parent',
  email: 'parent@example.test',
  displayName: 'E2E Parent',
  role: 'user',
  mode: 'instant',
  onboardingCompleted: true,
  childModeExitPasscodeConfigured: true,
  avatarUrl: null,
};

export const defaultChildModeSettings = {
  storyGenerationEnabled: true,
  storyContinuationEnabled: true,
  publicStoriesEnabled: true,
  dailyGenerationLimit: null,
  monthlyGenerationLimit: null,
  dailyAudioGenerationLimit: null,
  allowedThemeSlugs: [],
  allowedLanguageCodes: [],
  allowedCharacterIds: [],
  freeTextPromptsEnabled: true,
  audioGenerationEnabled: true,
  quizGenerationEnabled: true,
  parentReviewRequired: false,
  allowSiblingCharacters: false,
  allowSharedFamilyStories: true,
};

export const testChild = {
  id: 'child-e2e-1',
  name: 'Mira',
  storyCreationMode: 'artisan',
  age: {
    years: 6,
    months: 0,
    totalMonths: 72,
    ageGroup: '6-7',
    isBirthdayToday: false,
    daysUntilBirthday: 120,
  },
  childMode: {
    childModeEnabled: true,
    childModeSettings: defaultChildModeSettings,
    activeSessionCount: 0,
  },
};

export const testChildProfile = {
  ...testChild,
  birthDate: '2020-07-10',
  languages: ['en', 'es'],
  referencePhotos: [],
  turnaroundSheet: null,
  storyCreationMode: 'artisan',
  childModeEnabled: true,
  childModeSettings: defaultChildModeSettings,
  childModePasscodeConfigured: true,
  childModeActiveSessionCount: 0,
  authorPseudonym: 'Mira the Maker',
  authorAboutMe: 'I like careful comets and kind spells.',
};

export const testCharacter = {
  id: 'character-e2e-1',
  name: 'Luna',
  type: 'person',
  subtype: null,
  description: 'A brave friend with a blue scarf.',
  descriptionLanguage: 'en',
  childProfileId: null,
  referencePhotos: [],
  turnaroundSheet: null,
  appearanceTraits: null,
  personality: null,
};

export const storyThemes = {
  goals: [
    { slug: 'kindness', name: 'Kindness' },
    { slug: 'curiosity', name: 'Curiosity' },
  ],
  scenarioCards: [
    {
      id: 'magic_wizards',
      name: 'Magic wizards',
      description: 'A bright spell-filled adventure.',
      icon: '🪄',
    },
    {
      id: 'space_odyssey',
      name: 'Space odyssey',
      description: 'Planets, rockets, and gentle cosmic mysteries.',
      icon: '🚀',
    },
  ],
  ageGroups: [
    {
      id: 'age-4-5',
      slug: '4-5',
      nameKey: 'story.age_4_5',
      minMonths: 48,
      maxMonths: 71,
      sortOrder: 1,
    },
    {
      id: 'age-6-7',
      slug: '6-7',
      nameKey: 'story.age_6_7',
      minMonths: 72,
      maxMonths: 95,
      sortOrder: 2,
    },
    {
      id: 'age-8-9',
      slug: '8-9',
      nameKey: 'story.age_8_9',
      minMonths: 96,
      maxMonths: 119,
      sortOrder: 3,
    },
  ],
};

export const subscriptionUsage = {
  stories: { used: 1, limit: 30, remaining: 29 },
  graphicNovels: { used: 0, limit: 10, remaining: 10 },
  mixedStories: { used: 0, limit: 5, remaining: 5 },
  audio: { used: 0, limit: 30, remaining: 30 },
  resetsAt: '2026-08-01T00:00:00.000Z',
  currentPeriodEnd: '2026-08-01T00:00:00.000Z',
  subscriptionStatus: 'active',
  cancelAtPeriodEnd: false,
  paymentProvider: 'stripe',
  enableRealPayments: false,
};

const planFeatures = [
  { name: 'stories_per_month', value: { limit: 3 }, category: 'usage' },
  { name: 'audio_stories_per_month', value: { limit: 3 }, category: 'usage' },
  { name: 'graphic_novels_per_month', value: { limit: 0 }, category: 'usage' },
];

export const billingPlans = [
  {
    id: 'plan-e2e-free',
    slug: 'free',
    name: 'Free',
    description: 'A small starter plan.',
    priceMonthly: 0,
    pricingCurrency: 'EUR',
    sortOrder: 1,
    isActive: true,
    isCurrent: true,
    stripePriceConfigured: true,
    createdAt: '2026-07-01T00:00:00.000Z',
    updatedAt: '2026-07-01T00:00:00.000Z',
    features: planFeatures,
  },
  {
    id: 'plan-e2e-starter',
    slug: 'starter',
    name: 'Starter',
    description: 'More stories for the family.',
    priceMonthly: 999,
    pricingCurrency: 'EUR',
    sortOrder: 2,
    isActive: true,
    isCurrent: false,
    stripePriceConfigured: true,
    createdAt: '2026-07-01T00:00:00.000Z',
    updatedAt: '2026-07-01T00:00:00.000Z',
    features: [
      { name: 'stories_per_month', value: { limit: 30 }, category: 'usage' },
      { name: 'audio_stories_per_month', value: { limit: 30 }, category: 'usage' },
      { name: 'graphic_novels_per_month', value: { limit: 10 }, category: 'usage' },
    ],
  },
];

export const privateStories = [
  {
    id: 'private-story-magic-audio',
    title: 'Mira and the Moon Lantern',
    language: 'en',
    status: 'completed',
    scenarioCardId: 'magic_wizards',
    hasAudio: true,
    audioMetadata: { finalAssetId: 'audio-1' },
    coverImageUrl: null,
    coverThumbnailUrl: null,
    createdAt: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'private-story-child-review',
    title: 'Mira and the Careful Comet',
    language: 'en',
    status: 'completed',
    scenarioCardId: 'magic_wizards',
    hasAudio: false,
    audioMetadata: null,
    coverImageUrl: null,
    coverThumbnailUrl: null,
    createdAt: '2026-07-03T10:00:00.000Z',
    createdByMode: 'child',
    createdByChildProfileId: 'child-e2e-1',
    parentReviewStatus: 'pending',
  },
  {
    id: 'private-story-space',
    title: 'The Rocket That Learned to Whisper',
    language: 'es',
    status: 'completed',
    scenarioCardId: 'space_odyssey',
    hasAudio: false,
    audioMetadata: null,
    coverImageUrl: null,
    coverThumbnailUrl: null,
    createdAt: '2026-07-02T10:00:00.000Z',
  },
];

export const publicStories = [
  {
    id: 'public-story-magic-audio',
    title: 'The Singing Wand',
    publishedSlug: 'the-singing-wand',
    authorId: 'author-1',
    authorDisplayName: 'Aster',
    coverImageUrl: null,
    coverThumbnailUrl: null,
    hasAudio: true,
    audioMetadata: { finalAssetId: 'public-audio-1' },
    scenarioCardId: 'magic_wizards',
    language: 'en',
    ageGroup: '4-5',
    readingTimeMinutes: 4,
    rating: { avg: 4.8, count: 12 },
  },
  {
    id: 'public-story-space',
    title: 'The Quiet Planet Parade',
    publishedSlug: 'quiet-planet-parade',
    authorId: 'author-2',
    authorDisplayName: 'Nova',
    coverImageUrl: null,
    coverThumbnailUrl: null,
    hasAudio: false,
    audioMetadata: null,
    scenarioCardId: 'space_odyssey',
    language: 'es',
    ageGroup: '6-7',
    readingTimeMinutes: 8,
    rating: { avg: 4.5, count: 5 },
  },
  {
    id: 'public-story-long',
    title: 'A Very Long Map of Friendly Stars',
    publishedSlug: 'friendly-stars-map',
    authorId: 'author-3',
    authorDisplayName: 'Orion',
    coverImageUrl: null,
    coverThumbnailUrl: null,
    hasAudio: true,
    audioMetadata: { finalAssetId: 'public-audio-2' },
    scenarioCardId: 'space_odyssey',
    language: 'en',
    ageGroup: '8-9',
    readingTimeMinutes: 12,
    rating: { avg: 4.9, count: 7 },
  },
];

const moonLanternScenes = [
  {
    sceneId: 1,
    text: 'Mira found a moon lantern under the old willow and whispered the bravest hello.',
    image: {
      id: 'asset-moon-lantern-1',
      url: '/api/v1/assets/e2e/moon-lantern-1.png',
      mimeType: 'image/png',
      status: 'completed',
    },
    audio: null,
    artifactMention: null,
  },
  {
    sceneId: 2,
    text: 'The lantern glowed softly and showed her a path of silver stepping stones.',
    image: {
      id: 'asset-moon-lantern-2',
      url: '/api/v1/assets/e2e/moon-lantern-2.png',
      mimeType: 'image/png',
      status: 'completed',
    },
    audio: null,
    artifactMention: null,
  },
];

const childReviewScenes = [
  {
    sceneId: 1,
    text: 'Mira and the comet checked every star gate before flying through the quiet sky.',
    image: {
      id: 'asset-child-review-1',
      url: '/api/v1/assets/e2e/child-review-1.png',
      mimeType: 'image/png',
      status: 'completed',
    },
    audio: null,
    artifactMention: null,
  },
  {
    sceneId: 2,
    text: 'When the comet slowed down, Mira made a careful map back home.',
    image: {
      id: 'asset-child-review-2',
      url: '/api/v1/assets/e2e/child-review-2.png',
      mimeType: 'image/png',
      status: 'completed',
    },
    audio: null,
    artifactMention: null,
  },
];

export const privateStoryManifests = {
  'private-story-magic-audio': {
    ...privateStories[0],
    storyId: 'private-story-magic-audio',
    ageGroup: '6-7',
    isPublished: false,
    publishedSlug: null,
    visibility: null,
    shareUrl: null,
    coverAssetId: 'asset-moon-lantern-1',
    createdByMode: 'parent',
    createdByChildProfileId: null,
    parentReviewStatus: 'not_required',
    fullText: moonLanternScenes.map((scene) => scene.text).join('\n\n'),
    scenes: moonLanternScenes,
    characters: [],
    readingSettings: {
      baseTextSizePx: 20,
      textSizeMultiplier: 1,
      textSizePx: 20,
    },
    imageGenerationComplete: true,
    sceneIdsWithImages: [1, 2],
    failedScenes: [],
    metadata: { storyFormat: 'story' },
  },
  'private-story-child-review': {
    ...privateStories[1],
    storyId: 'private-story-child-review',
    ageGroup: '6-7',
    isPublished: false,
    publishedSlug: null,
    visibility: null,
    shareUrl: null,
    coverAssetId: 'asset-child-review-1',
    fullText: childReviewScenes.map((scene) => scene.text).join('\n\n'),
    scenes: childReviewScenes,
    characters: [],
    readingSettings: {
      baseTextSizePx: 20,
      textSizeMultiplier: 1,
      textSizePx: 20,
    },
    imageGenerationComplete: true,
    sceneIdsWithImages: [1, 2],
    failedScenes: [],
    metadata: { storyFormat: 'story' },
  },
  'private-story-space': {
    ...privateStories[2],
    storyId: 'private-story-space',
    ageGroup: '6-7',
    isPublished: false,
    publishedSlug: null,
    visibility: null,
    shareUrl: null,
    coverAssetId: null,
    createdByMode: 'parent',
    createdByChildProfileId: null,
    parentReviewStatus: 'not_required',
    fullText: 'The rocket learned to whisper so sleeping planets could keep dreaming.',
    scenes: [
      {
        sceneId: 1,
        text: 'The rocket learned to whisper so sleeping planets could keep dreaming.',
        image: null,
        audio: null,
        artifactMention: null,
      },
    ],
    characters: [],
    readingSettings: {
      baseTextSizePx: 20,
      textSizeMultiplier: 1,
      textSizePx: 20,
    },
    imageGenerationComplete: true,
    sceneIdsWithImages: [],
    failedScenes: [],
    metadata: { storyFormat: 'story' },
  },
};
