-- Migration: Create schema_migrations table and backfill all existing migrations as applied
-- Created: 2026-03-07
-- Use when migrations were run manually and journal needs to be synced

CREATE TABLE IF NOT EXISTS schema_migrations (
  filename VARCHAR(255) PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO schema_migrations (filename) VALUES
  ('0001_complete_schema.sql'),
  ('0003_add_plans_features_profiles_characters.sql'),
  ('0004_add_stories_and_config.sql'),
  ('0005_add_m4_image_generation.sql'),
  ('0006_add_performance_indexes.sql'),
  ('0007_add_m5_audio_generation.sql'),
  ('0008_add_voice_catalog_and_age_groups.sql'),
  ('0008_add_voice_catalog_and_age_groups_fixed.sql'),
  ('0009_add_audio_scene_group_index.sql'),
  ('0009_add_professional_plan.sql'),
  ('0009_add_translations_table.sql'),
  ('0010_update_goals_and_scenarios.sql'),
  ('0011_add_scenario_guidance.sql'),
  ('0011_add_stories_metadata.sql'),
  ('0012_add_stories_audio_metadata.sql'),
  ('0012_increase_story_length.sql'),
  ('0013_add_scary_stories_theme.sql'),
  ('0013_add_story_request_intermediate_data.sql'),
  ('0014_add_story_requests_selected_characters.sql'),
  ('0014_cooing_ironclad.sql'),
  ('0015_add_story_requests_image_style.sql'),
  ('0016_add_story_requests_selected_children.sql'),
  ('0017_add_ai_generated_descriptions.sql'),
  ('0018_revert_age_group_id_not_null.sql'),
  ('0019_rename_plans_and_migrate_audio.sql'),
  ('0020_add_golden_stars_plan.sql'),
  ('0021_fix_plan_sort_and_limits.sql'),
  ('0022_reset_audio_story_limits.sql'),
  ('0023_update_plan_limits.sql'),
  ('0024_add_display_name_to_voices.sql'),
  ('0024_add_french_german_scenario_translations.sql'),
  ('0024_add_voice_sample_url.sql'),
  ('0025_add_story_series.sql'),
  ('0026_add_scene_character_tracking.sql'),
  ('0027_restrict_premium_voices_to_fairyworld.sql'),
  ('0028_restrict_series_to_golden_and_above.sql'),
  ('0029_fix_scene_text_502c5782.sql'),
  ('0030_add_character_turnaround_sheet.sql'),
  ('0031_add_character_description_en.sql'),
  ('0032_add_child_turnaround_sheet.sql'),
  ('0033_add_child_description_en.sql'),
  ('0034_add_scenario_plot_examples.sql'),
  ('0035_add_character_is_hidden.sql'),
  ('0036_add_user_mode.sql'),
  ('0037_simplify_character_types.sql'),
  ('0038_rename_pet_to_animal.sql'),
  ('0039_add_asset_thumbnails.sql'),
  ('0040_add_scenario_world_rules.sql'),
  ('0041_add_expeditions_and_macro_scifi.sql'),
  ('0042_update_macro_scifi_icon.sql'),
  ('0043_add_environment_image_cache.sql'),
  ('0044_remove_story_tones.sql'),
  ('0045_add_publish_fields.sql'),
  ('0046_normalize_asset_urls_to_relative.sql'),
  ('0047_add_public_render_version.sql'),
  ('0048_add_alignments_table.sql'),
  ('0049_add_visibility_and_share_token.sql'),
  ('0050_add_share_card_scene_id.sql'),
  ('0051_fix_is_published_default.sql'),
  ('0052_create_schema_migrations.sql')
ON CONFLICT (filename) DO NOTHING;
